### ISSUE TITLE
Apache not loading after enable IP2Location Module

### ISSUE THREAD

**Issue by amit-ahire** [ip2location/ip2location-apache#1]
Hi,
I follow all the steps mentioned in the readme.
I'm using ubuntu 16.04 LTS version.
Can any one help me in finding solution for below error.?

apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/IP2Location.load: Cannot load /usr/lib/apache2/modules/mod_ip2location.so into server: /usr/lib/apache2/modules/mod_ip2location.so: undefined symbol: IP2Location_open
Action 'configtest' failed.

**Comment by ip2location-com** [comment]
Can you please check if there any errors during compilations?

**Comment by jgun** [comment]
You need to set this environment variable before (re)starting your apache
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/apache2/modules/
$ export LD_LIBRARY_PATH

Following links were useful to understand better
https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s
http://www.gnu.org/software/gsl/manual/html_node/Shared-Libraries.html

**Comment by MrFunken** [comment]
Okay, and what should I do if that does not work?

**Comment by ip2location-com** [comment]
Can you please refer to https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s and check which is your shared library path?
