### ISSUE TITLE
very weird results on IP2LOCATION_COUNTRY_SHORT logging/filtering

### ISSUE THREAD

**Issue by wienfuchs** [ip2location/ip2location-apache#2]
When using this (tested both on a recent Ubuntu 18.04 or 20.04 LTS) with some load, it produces very weird results on IP2LOCATION_COUNTRY_SHORT. I would expect only short country codes to be logged, but here's what I get - and therefore cannot really use in a production enviroment to restrict access.

**Steps I've done and how to reproduce it:**

- set up a Ubuntu server with apache2, ssl, maybe phpmyadmin for quick testing to produce "load"
- download, compile and install https://github.com/ip2location/IP2Location-C-Library/
- download, compile and install https://github.com/ip2location/ip2location-apache/
- download a recent IP2LOCATION-LITE-DB1.BIN e.g. to /usr/share/ip2location/IP2LOCATION-LITE-DB1.BIN
- enable an apache conf as per README.md
- enable logging in an enabled site by ``LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" \"%{IP2LOCATION_COUNTRY_SHORT}e\"" location`` and ``CustomLog ${APACHE_LOG_DIR}/location.log location``
- fiddle around in your phpmyadmin
- parse resulting location.log with ``cat location.log | awk '{print $NF}' | sort -u``

_Below samples are unfiltered_

**Sample result (all access to /phpmyadmin from same sourced in Austria so one would expect only single line "AT"):**
```"
"-"
""
a"
"AT"
"AU"
Faso\x02BG\bBulgaria\x02BH\x07Bahrain\x02BI\x07B"
Firefox/78.0"
Herzegovina\x02BB\bBarbados\x02BD\nBangladesh\x02BE\x07Belgium\x02BF\x0cB"
+info@netcraft.com)"
Islands"
Islands\x02AZ\nAzerbaijan\x02BA\x16"
Islands\x02AZ\nAzerbaijan\x02BA\x16Bo"
"T\x07"
"\x02"
"\x1a)\xd4\x02"
"\x1e"
"\xa0\xa5\x1e"
"\xbe\x02"
```
**Sample result on new Ubuntu 20 server without any content, used phpmyadmin and left staling some hours (mainly bot access therefore):**
```"
""
"-"
-
-"
'A"
Africa\x02ZM\x06Zambia\x02ZW\bZimbabwe\x05'Adan\x06'Ajlun\x06'Ajma
"Akita"
apskritis\tVinh"
'Asi
"AT"
AT
AT"
Balq
Balq"
"BE"
Beach\x06Veroia\vVerolanuova\x05
connection)"
Firefox/78.0"
"gailhenc\tVillejuif\tVillejust\nVillelaure\x0cVillemandeur\x0cVillemoirieu\x0cVillemontais\x10Villemoustaussou\x07Ville"
Hills\x06Vestby\bVestbygd\x06Vestec\tVestmanna\x0eVestmannaeyjar\x07Vestnes\bVeszprem\x06"
"NL"
NL
of)\x02IS\x07Iceland\x02IT\x05Italy\x02JE\x06Jersey\x02JM\x07Jamaica\x02JO\x06Jordan\x02JP\x05Japan\x02KE\x05Kenya\x02KG\nKy
Safari/537.36"
Thuan\x10Binshan"
"US"
"\x04\x14\n"
"{\x06"
{\x06
"\xb7\x84"
\xb7\x84
\xb7\x84"
```

**Sample result on U20 with only access from single 192.168.x.x client without quotes in LogFormat:**
```
-
AD
Emirates\x02AF\vAfg
Firefox/78.0"
US
\x02
\x14
\x14\v
\x1b\x02
\x1e
\x9c
\xa1\x1e
)\xd4\x02
```

**Comment by ip2location-com** [comment]
Can you provide the original log instead of the log that parsed by awk?

**Comment by wienfuchs** [comment]
One could simply produce an own log - GDPR/DSGVO prevents publically posted logs. But I quickly produced one for you, using an "anonymised combined" format ``LogFormat "%l %l %l %t \"%l\" %>s %O \"%l\" \"%l\" \"%{IP2LOCATION_COUNTRY_SHORT}e\"" locationonly`` - attached - I only used phpmyadmin on a local machine to produce it:

[location.log](https://github.com/ip2location/ip2location-apache/files/5627231/location.log)

**Comment by ip2location-com** [comment]
Please use the latest commit from https://github.com/chrislim2888/IP2Location-Apache-Module
