### ISSUE TITLE
Error: HTTPD.CONF SYNTAX CHECK RESULTS

### ISSUE THREAD

**Issue by chainagents** [ip2location/ip2location-apache#3]
Hi, I am using Apache 2.4.46 with Interworx control panel. I wanted to install IP2Location module and after installation of IP2Location Apache module I get this error:

httpd: Syntax error on line 101 of /etc/httpd/conf/httpd.conf: Cannot load /usr/lib64/httpd/modules/mod_ip2location.so into server: libIP2Location.so: cannot open shared object file: No such file or directory

More info on line 101:
101. LoadModule IP2Location_module /usr/lib64/httpd/modules/mod_ip2location.so
102. #
103. Include conf.modules.d/*.conf

I used sudo find / -name mod_ip2location.so to find the path I got this:
/root/IP2Location-Apache-Module-master/.libs/mod_ip2location.so
/usr/lib64/httpd/modules/mod_ip2location.so

**Comment by chainagents** [comment]
**Update:**
I used these two lines and it fixed my problem but I have a new problem:

$ sudo sh -c "echo /usr/local/lib  >> /etc/ld.so.conf.d/local.conf"
$ ldconfig

**The new problem:**
Everything is installed as said here: https://www.ip2location.com/development-libraries/ip2location/apache
The below image shows that it is enabled
![ENABLE](https://user-images.githubusercontent.com/77523392/104806441-08b8dd80-57f1-11eb-8791-0e5670eac70b.PNG)
Also added these tree lines of codes to my website's .htaccess:
_RewriteEngine On
RewriteCond %{ENV:IP2LOCATION_COUNTRY_SHORT} ^AM$
RewriteRule ^(.*)$ http://www.google.com/$1 [L]_
But does not redirect me does google. Any suggestions?

**Comment by ip2location-com** [comment]
Can you check what is the IP address detected in the Apache log?

**Comment by chainagents** [comment]
Thank you for your reply.

How can I check that? I'm sorry, I am a newbie in that field.

BTW I tried different IP's but still not getting redirected.

**Comment by chainagents** [comment]
I told you was a newbie, I forgot to download the database. :DD

Everything works fine now. I hope at least the first problem which I solved by those two lines of codes, will help someone.

Thank you again!
