### ISSUE TITLE
mod_ip2location is not picking up Client IP as set by mod_remoteip

### ISSUE THREAD

**Issue by blaksec** [ip2location/ip2location-apache#4]
I have a situation where my services are behind a proxy. I utilize mod_remoteip to overwrite Client-IP with the one passed via a custom header which is set by said proxy.  I'm confident that part works as I can see IP passed via that header as I can see it reflected in my app logs and in apache logs (logged as %a). 

I was thinking to modify mod_ip2location to pick up that custom header but unfortunately mod_remoteip discards it the moment IP is extracted. 

Using X-Forwarded-For will not work for us as it would allow end user to manipulate business logic by modifying the value of X-Forwarded-For. Custom header we use cannot be manipulated by the end user.  Besides, and this might be a topic for a separate issue, the way proxy works, X-Forwarded-For often contains 2+ comma separated IPs which seems to be breaking mod_ip2location logic, resulting in INVALID V4 ADDRESS.

**Comment by ip2location-com** [comment]
Please configure your proxy to set IP without commas in the X-Forwarded-For headers or this will not going to work.
